#    指定端口号
server:
  port: 8899
  elasticsearch:
    rest:
      uris: http://88loveyou.com:9200
stukk:
  elasticsearch:
    host: 你的服务器ip:9200
    username: 你的账号
    password: 你的密码
    connectTimeout: 5000
    socketTimeout: 5000
    connectionRequestTimeout: 5000
    maxConnectNum: 100
    maxConnectPerRoute: 100
